runtime: nodejs18
instance_class: F2
env_variables:
  DB_HOST: "34.77.149.113"
  DB_USER: "root"
  DB_PASS: ""
  DB_NAME: "casino"
beta_settings:
  cloud_sql_instances: "interfaces-425016:europe-west1:iu"
